### ISSUE TITLE
Change name of .clang-format to _clang-format

### ISSUE THREAD

**Issue by vbadeasv** [haaakon/Apple-clang-format#5]
Since clang-format supports both ".clang-format" and "_clang-format" file names, wouldn't be better to use the latter? That's because ".clang-format" will be, by default, hidden in both Finder and Terminal, so will be harder to find. Additionally, I think it's more explicit to see, near a project file, a visible "format" file.

**Comment by haaakon** [comment]
Really good point. I suuport it, will update when i have the time

**Comment by apwelsh** [comment]
Coming into this a bit late.  I think .clang-format adheres to unix naming notations.  Easy enough to rename it back.
